name: MCServerAPI
version: @version@
main: work.lclpnet.serverimpl.bukkit.MCServerBukkit
api-version: 1.14
authors: [ LCLP ]
description: LCLPNetwork integration for Minecraft Bukkit servers.
website: https://lclpnet.work

commands:
  mclink:
    description: Link your Minecraft account with your LCLPNetwork account.
  stats:
    description: View a player's stats.
  language:
    description: Set your preferred language.
    aliases: [lang]
